global:
  scrape_interval: 180s
  scrape_timeout: 10s

scrape_configs:
  - job_name: api-scrape
    metrics_path: /metrics/api
    static_configs:
      - targets: ["metrics:3500"]
  - job_name: api-v2-scrape
    metrics_path: /metrics/api-v2
    static_configs:
      - targets: ["metrics:3500"]
